# Look in the tasks/setup.rb file for the various options that can be
# configured in this Rakefile. The .rake files in the tasks directory
# are where the options are used.

begin
  require 'bones'
  Bones.setup
rescue LoadError
  begin
    load 'tasks/setup.rb'
  rescue LoadError
    # raise RuntimeError, '### please install the "bones" gem ###'
  end
end

ensure_in_path 'lib'
require 'ruby_bloomberg'

task :default => 'spec:run'

PROJ.name = 'ruby_bloomberg'
PROJ.authors = 'Ana Nelson'
PROJ.email = 'ana@ananelson.com'
PROJ.url = 'http://bloombergapi.com'
PROJ.version = RubyBloomberg::VERSION
PROJ.rubyforge.name = 'ruby_bloomberg'

PROJ.spec.opts << '--color'
